package com.mobashop99.pharaoh;

import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.provider.Settings;import android.view.*;import android.widget.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.*;import android.text.*;import org.json.*;import java.text.*;import java.util.*;import java.net.*;import java.io.*;

public class MainActivity extends Activity{
 int bg=Color.rgb(7,16,29), card=Color.rgb(17,33,50), stroke=Color.rgb(0,190,255), green=Color.rgb(94,242,171), gold=Color.rgb(255,184,62); LinearLayout root,chat,orders; ScrollView scroll; String game="",pack="",playerId="",playerName="",phone="",pay="InstaPay",shot=""; SharedPreferences sp;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);sp=getSharedPreferences("moba",0);showMain();}
 TextView tv(String s,int size,int c,int style){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,style);v.setGravity(Gravity.RIGHT);v.setPadding(12,8,12,8);return v;}
 TextView btn(String s,int c){TextView v=tv(s,15,Color.WHITE,Typeface.BOLD);v.setGravity(Gravity.CENTER);GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(24);g.setStroke(1,Color.argb(160,255,255,255));v.setBackground(g);v.setPadding(18,14,18,14);return v;}
 GradientDrawable bgd(int c,int st){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(26);g.setStroke(1,st);return g;}
 void showMain(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(14,14,14,14);setContentView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(6,4,6,10);ImageView logo=new ImageView(this);logo.setImageResource(getResources().getIdentifier("moba_logo","drawable",getPackageName()));head.addView(logo,new LinearLayout.LayoutParams(dp(54),dp(54)));TextView title=tv("MOBA SHOP99\nDigital Store For Gamers",18,Color.WHITE,Typeface.BOLD);title.setGravity(Gravity.RIGHT);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);
 LinearLayout tabs=new LinearLayout(this);tabs.setGravity(Gravity.CENTER);TextView t1=btn("فرعون المساعد",stroke);TextView t2=btn("سجل الطلبات",Color.rgb(42,52,70));tabs.addView(t1,new LinearLayout.LayoutParams(0,dp(52),1));tabs.addView(t2,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(tabs);FrameLayout frame=new FrameLayout(this);root.addView(frame,new LinearLayout.LayoutParams(-1,0,1));Runnable ph=()->{frame.removeAllViews();frame.addView(pharaohView());t1.setBackground(bgd(stroke,Color.WHITE));t2.setBackground(bgd(Color.rgb(42,52,70),Color.DKGRAY));};Runnable or=()->{frame.removeAllViews();frame.addView(orderView());t2.setBackground(bgd(stroke,Color.WHITE));t1.setBackground(bgd(Color.rgb(42,52,70),Color.DKGRAY));};t1.setOnClickListener(v->ph.run());t2.setOnClickListener(v->or.run());ph.run();}
 View pharaohView(){scroll=new ScrollView(this);chat=new LinearLayout(this);chat.setOrientation(LinearLayout.VERTICAL);chat.setPadding(0,14,0,20);scroll.addView(chat);cardHeader();bot("اهلا بيك في فرعون مساعد MOBA SHOP99 👑\nاختار اللعبة والباقه واكتب بياناتك وارفع سكرين التحويل.");mainChoices();return scroll;}
 void cardHeader(){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER);c.setPadding(12,12,12,12);c.setBackground(bgd(card,stroke));ImageView p=new ImageView(this);p.setImageResource(getResources().getIdentifier("pharaoh","drawable",getPackageName()));c.addView(p,new LinearLayout.LayoutParams(dp(70),dp(70)));TextView x=tv("Assistant فرعون\nمساعد الشحن والمتابعة",18,Color.WHITE,Typeface.BOLD);c.addView(x,new LinearLayout.LayoutParams(0,-2,1));chat.addView(c,new LinearLayout.LayoutParams(-1,-2));}
 void bot(String s){TextView v=tv(s,17,Color.WHITE,Typeface.NORMAL);v.setBackground(bgd(Color.rgb(30,45,58),Color.rgb(154,125,54)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,12,0,6);chat.addView(v,lp);}
 void me(String s){TextView v=tv(s,16,Color.WHITE,Typeface.BOLD);v.setGravity(Gravity.LEFT);v.setBackground(bgd(Color.rgb(12,68,75),stroke));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,8,0,4);chat.addView(v,lp);}
 void mainChoices(){grid(new String[]{"ابدأ شحن","سجل الطلبات","طرق الدفع","الدعم"}, new Runnable[]{()->chooseGame(),()->{root.removeAllViews();showMain();},()->paymentInfo(),()->bot("للدعم تواصل على Telegram: @MOBASHOP99")});}
 void grid(String[] names,Runnable[] acts){LinearLayout row=null;for(int i=0;i<names.length;i++){if(i%2==0){row=new LinearLayout(this);chat.addView(row,new LinearLayout.LayoutParams(-1,-2));}TextView b=btn(names[i], i==0?gold:Color.rgb(45,58,76));final int k=i;b.setOnClickListener(v->acts[k].run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(55),1);lp.setMargins(5,6,5,6);row.addView(b,lp);} }
 void chooseGame(){me("ابدأ شحن");bot("اختار اللعبة اللي عايز تشحنها");String[] games={"PUBG Mobile","TikTok","Free Fire","Roblox","Valorant","eFootball","Last War","Yalla Ludo"};Runnable[] a=new Runnable[games.length];for(int i=0;i<games.length;i++){final String g=games[i];a[i]=()->{game=g;choosePack();};}grid(games,a);}
 void choosePack(){me(game);bot("اختار الباقة");String[] packs=game.contains("PUBG")?new String[]{"60 UC","325 UC","660 UC","1800 UC","3850 UC","8100 UC","Prime","Prime Plus"}:new String[]{"باقة 1","باقة 2","باقة 3","باقة خاصة"};Runnable[] a=new Runnable[packs.length];for(int i=0;i<packs.length;i++){final String p=packs[i];a[i]=()->{pack=p;askData();};}grid(packs,a);}
 void askData(){me(pack);bot("اكتب بيانات الطلب");EditText id=input("ID الحساب");EditText name=input("اسم الحساب");EditText mob=input("رقم الموبايل للمتابعة");TextView next=btn("التالي",green);next.setTextColor(Color.rgb(5,20,25));chat.addView(id);chat.addView(name);chat.addView(mob);chat.addView(next,new LinearLayout.LayoutParams(-1,dp(55)));next.setOnClickListener(v->{playerId=id.getText().toString();playerName=name.getText().toString();phone=mob.getText().toString();if(playerId.length()<3||phone.length()<5){bot("راجع ID ورقم الموبايل الاول.");return;}paymentInfo();});}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setGravity(Gravity.RIGHT);e.setSingleLine(true);e.setPadding(14,6,14,6);e.setBackground(bgd(Color.rgb(5,12,24),stroke));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(55));lp.setMargins(0,7,0,7);e.setLayoutParams(lp);return e;}
 void paymentInfo(){bot("بيانات الدفع InstaPay\nUser: "+Config.INSTAPAY_USER+"\nPhone: "+Config.INSTAPAY_PHONE+"\nName: "+Config.INSTAPAY_NAME);TextView open=btn("فتح لينك InstaPay",green);open.setTextColor(Color.rgb(5,20,25));chat.addView(open,new LinearLayout.LayoutParams(-1,dp(55)));open.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Config.INSTAPAY_URL)));}catch(Exception e){bot("مش قادر افتح اللينك من الجهاز ده.");}});bot("بعد التحويل ارجع هنا وارفع سكرين التحويل");TextView pick=btn("اختار صورة التحويل",green);pick.setTextColor(Color.rgb(5,20,25));chat.addView(pick,new LinearLayout.LayoutParams(-1,dp(55)));pick.setOnClickListener(v->{Intent in=new Intent(Intent.ACTION_OPEN_DOCUMENT);in.addCategory(Intent.CATEGORY_OPENABLE);in.setType("image/*");startActivityForResult(in,77);});TextView send=btn("ارسال الطلب",gold);chat.addView(send,new LinearLayout.LayoutParams(-1,dp(58)));send.setOnClickListener(v->submit());}
 public void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==77&&c==RESULT_OK&&d!=null){shot=d.getData().toString();bot("تم اختيار صورة التحويل ✅");}}
 void submit(){if(game.length()==0||pack.length()==0){bot("ابدأ شحن الاول واختار اللعبة والباقه.");return;}if(shot.length()==0){bot("ارفع سكرين التحويل قبل ارسال الطلب.");return;}try{JSONArray arr=new JSONArray(sp.getString("orders","[]"));JSONObject o=new JSONObject();String no="MOBA-"+(1000+arr.length()+1);o.put("no",no);o.put("game",game);o.put("pack",pack);o.put("id",playerId);o.put("name",playerName);o.put("phone",phone);o.put("status","قيد المراجعة");o.put("time",new SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.US).format(new Date()));arr.put(o);sp.edit().putString("orders",arr.toString()).apply();bot("تم تسجيل طلبك ✅\nرقم الطلب: "+no+"\nتابع حالته من سجل الطلبات.");sendTelegram(o);}catch(Exception e){bot("حصل خطأ في حفظ الطلب.");}}
 View orderView(){ScrollView s=new ScrollView(this);orders=new LinearLayout(this);orders.setOrientation(LinearLayout.VERTICAL);orders.setPadding(0,14,0,20);s.addView(orders);orders.addView(tv("سجل الطلبات",24,Color.WHITE,Typeface.BOLD));try{JSONArray arr=new JSONArray(sp.getString("orders","[]"));if(arr.length()==0)orders.addView(tv("لسه مفيش طلبات محفوظة على الجهاز ده.",17,Color.LTGRAY,Typeface.NORMAL));for(int i=arr.length()-1;i>=0;i--){JSONObject o=arr.getJSONObject(i);TextView v=tv("طلب: "+o.getString("no")+"\n"+o.getString("game")+" | "+o.getString("pack")+"\nID: "+o.getString("id")+"\nالحالة: "+o.getString("status")+"\nالوقت: "+o.getString("time"),16,Color.WHITE,Typeface.NORMAL);v.setBackground(bgd(card,stroke));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,10,0,8);orders.addView(v,lp);} }catch(Exception e){}return s;}
 void sendTelegram(JSONObject o){if(Config.TELEGRAM_BOT_TOKEN.length()<5)return;new Thread(()->{try{String text="طلب جديد MOBA SHOP99\n"+o.toString();String u="https://api.telegram.org/bot"+Config.TELEGRAM_BOT_TOKEN+"/sendMessage?chat_id="+Config.TELEGRAM_CHAT_ID+"&text="+URLEncoder.encode(text,"UTF-8");new URL(u).openStream().close();}catch(Exception ignored){}}).start();}
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);} }
